name: CI

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
  schedule:
    # run once a month (on the 3rd)
    - cron: "5 6 3 * *"

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        coq_version:
          - "8.18"
          - dev
        ocaml_version: ["4.14-flambda"]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: coq-community/docker-coq-action@v1
        with:
          opam_file: "seplogic-demo.opam"
          coq_version: ${{ matrix.coq_version }}
          ocaml_version: ${{ matrix.ocaml_version }}
          custom_script: |
            startGroup Add Iris repo
              opam repo add iris-dev https://gitlab.mpi-sws.org/iris/opam.git
            endGroup
            startGroup Print opam config
              opam config list; opam repo list; opam list
            endGroup
            startGroup Build dependencies
              opam pin add -n -y -k path $PACKAGE $WORKDIR
              opam update -y
              opam install -y -j 2 $PACKAGE --deps-only
            endGroup
            startGroup Build
              opam install -y -v -j 2 $PACKAGE
              opam list
            endGroup
            startGroup Uninstallation test
              opam remove $PACKAGE
            endGroup
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        if: github.ref == 'refs/heads/master'
        with:
          path: ./docs

  # Deployment job
  deploy:
    needs: build
    environment:
      name: "github-pages"
      url: ${{ steps.deployment.outputs.page_url }}
    concurrency:
      group: "pages"
      cancel-in-progress: true
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
